import mongoose from "mongoose";
import RoleModel from "../models/roleDoc";
import UserModel from "../models/userDoc";
import UserRoleModel from "../models/userRoleDoc";
import { Config } from "../config";
import bcrypt from "bcryptjs";

const data = {
  username: "new admin",
  email: "admin12@gmail.com",
  password: "12",
  role: "ADMIN",
};

const AutoGeneratedEntry = async () => {
  await mongoose.connect(Config.mongodbUrl);

  const userModel = new UserModel();
  const roleModel = new RoleModel();
  const userRoleModel = new UserRoleModel();

  userModel.username = data.username;
  userModel.email = data.email;
  const hashPassword = await bcrypt.hash(data.password, 10);
  userModel.password = hashPassword;

  if (data.role == "ADMIN") roleModel.roleName = "ADMIN";
  if (data.role == "SUPER ADMIN") roleModel.roleName = "SUPER ADMIN";

  const currentRole = await roleModel.save();
  userModel.roleId = currentRole._id;

  const user = await userModel.save();

  userRoleModel.roleId = currentRole._id;
  userRoleModel.userId = user._id;

  await userRoleModel.save();

  console.log("Seeded : Auto Generate Entry ", data);
};

AutoGeneratedEntry();
