## testing 

POST  http://localhost:4000/account/register
Content-Type: application/json

{
     "username" : "varun joshi",
     "email" :  "varunjoshi1590@gmail.com",
     "password"  : "12"
}


### LOGIN

POST  http://localhost:4000/account/login
Content-Type: application/json

{
     "email" :  "varunjoshi1590@gmail.com",
     "password"  : "12"
}



### EMPLOYEE LOGIN 

POST http://localhost:4000/account/employee-login
Content-Type: application/json
Authorization: Be

{
     "email" :  "varunjoshi12@gmail.com",
     "passcode"  : "12"
}